services:
  namenode:
    image: apache/hadoop:3.3.6
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
      - "8020:8020"
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./volumes/namenode:/data
      - ./data:/input-data
    networks:
      - spark-network

  datanode:
    image: apache/hadoop:3.3.6
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    volumes:
      - ./volumes/datanode:/data
    networks:
      - spark-network

  resourcemanager:
    image: apache/hadoop:3.3.6
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
    networks:
      - spark-network

  nodemanager:
    image: apache/hadoop:3.3.6
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
    networks:
      - spark-network

  spark-master:
    image: spark:4.0.1-java21
    hostname: spark-master-bike
    container_name: spark-master-bike
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MASTER_HOST=spark-master-bike
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "7078:7077"
      - "8086:8080"
      - "4041:4040"
    depends_on:
      - namenode
    volumes:
      - ./target:/opt/spark-apps
      - ./data:/input-data
    env_file:
      - ./config
    networks:
      - spark-network

  spark-worker-1:
    image: spark:4.0.1-java21
    hostname: spark-worker-1-bike
    container_name: spark-worker-1-bike
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-bike:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./target:/opt/spark-apps
      - ./data:/input-data
    env_file:
      - ./config
    networks:
      - spark-network

  spark-worker-2:
    image: spark:4.0.1-java21
    hostname: spark-worker-2-bike
    container_name: spark-worker-2-bike
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-bike:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    volumes:
      - ./target:/opt/spark-apps
      - ./data:/input-data
    env_file:
      - ./config
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge